name: common
description: Flutter Showcase Collection,  Sample Code and Component wise Code.
publish_to: 'none'

version: 1.0.0+1
environment:
    sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dep_management:
    path: ../dep_management
  design_system:
    path: ../core/design-system


flutter:
  uses-material-design: true

